name = "grindroom"
compatibility_date = "2026-03-11"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_APP_URL = "https://grindroom.nishantborse-2008.workers.dev"
